name: Update Lock Files and Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  update-lock-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (if applicable)
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Change to your desired Node.js version

      - name: Install dependencies and update lock file
        run: |
          npm update

      - name: Check for changes
        id: check-changes
        run: |
          git diff --exit-code || echo "Changes detected"
        continue-on-error: true

      - name: Commit changes
        if: steps.check-changes.outcome == 'success'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update lock files [skip ci]" # Use a meaningful commit message
          git push
